# Generated by Django 4.2.2 on 2023-07-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_create_teachers_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'учитель', 'verbose_name_plural': 'учителя'},
        ),
        migrations.AlterModelManagers(
            name='courses',
            managers=[
            ],
        ),
    ]
